VALID_ACTIONS = {
    "notify",
    "digest",
    "mute"
}

VALID_TYPES = {
    "personal",
    "urgent",
    "event",
    "payment",
    "business_update",
    "promotion",
    "greeting",
    "forward",
    "spam",
    "scam",
    "unknown"
}


def validate_prediction(result):
    """
    Validate and clean Gemini's prediction.
    Ensures the output matches the hackathon requirements.
    """

    # -------------------------
    # Action
    # -------------------------
    action = str(result.get("action", "digest")).lower()

    if action not in VALID_ACTIONS:
        action = "digest"

    # -------------------------
    # Message Type
    # -------------------------
    message_type = str(
        result.get("message_type", "unknown")
    ).lower()

    if message_type not in VALID_TYPES:
        message_type = "unknown"

    # -------------------------
    # Reason
    # -------------------------
    reason = str(result.get("reason", "")).strip()

    if len(reason) == 0:
        reason = "Generated by AI."

    # -------------------------
    # Confidence
    # -------------------------
    try:
        confidence = float(result.get("confidence", 0.75))
    except Exception:
        confidence = 0.75

    confidence = max(0.0, min(1.0, confidence))

    return {
        "action": action,
        "message_type": message_type,
        "reason": reason,
        "confidence": round(confidence, 2)
    }